
version: "branch-{branch}-build-nr-{build}"
skip_tags: true
environment:
  global:
    STACK_ROOT: C:\sr

skip_commits:
  files:
    - '**\*.md'

build: off

install:
  - git submodule update --init --recursive
  - curl -s -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
  - 7z x stack.zip stack.exe > NUL
  - set PATH=%PATH%;C:\Stack
  - mkdir C:\Stack
  - move stack.exe C:\Stack\
  - .\cef3-simple\cef3-raw\scripts\setup.bat

build_script:
  - stack setup --skip-msys --no-terminal > NUL
  - cd cef3-simple\cef3-raw
  - .\scripts\configure.bat
  - cd ..\..
  - stack install

after_build:
  - md result\static\css
  - xcopy /E /Q %CEF3_PATH%\Release\* result\
  - xcopy /E /Q %CEF3_PATH%\Resources\* result\
  - xcopy /Q %APPDATA%\local\bin\tmr.exe result\
  - xcopy /Q resources\semantic.min.css result\static\css
  - dir result
  - cd result
  - 7z a tmr.7z *
  - 7z a tmr-exe.7z tmr.exe

artifacts:
  - path: result\tmr.7z
    name: Full App
  - path: result\tmr-exe.7z
    name: Exe Only

cache:
  - C:\sr -> .appveyor.yml
